version: '3'
networks:
    service:
    secured:

services:
    camera:
        build:
            context: .
            dockerfile: Dockerfile.ubuntu
        network_mode: host
        privileged: true
        volumes:
            - ./app:/app
        env_file: .env
        user: "${STORAGE_UID}:${STORAGE_GID}"
        restart: always
