version: '3'
networks:
    service:
    secured:

services:
    camera:
        build:
            context: .
            dockerfile: Dockerfile.openvino

        network_mode: host
        privileged: true
        volumes:
            - ./app/storage:/app/storage
        env_file: .env
        restart: always
