FROM openvino/ubuntu18_runtime:latest

USER root

ENV DEBIAN_FRONTEND "noninteractive"

RUN apt-get update
RUN apt-get install -y python3-dev libavahi-compat-libdnssd-dev ffmpeg gcc

RUN mkdir /app
# ADD app /app/app
# ADD web/dist /app/web/dist

WORKDIR /app/app

VOLUME /app/app
VOLUME /app/web/dist
VOLUME /app/storage

CMD ["/app/app/run.sh"]