version: '3'
networks:
    service:
    secured:

services:
    camera:
        build:
            context: .
            dockerfile: Dockerfile.openvino
            args:
                - STORAGE_UID=${STORAGE_UID}
                - STORAGE_GID=${STORAGE_GID}
                - STORAGE_USER=${STORAGE_USER}

        network_mode: host
        privileged: true
        volumes:
            - ./app:/app
        env_file: .env
        restart: always
